name: Bug
description: Report an issue with the game
title: "[0.1.0] "
labels: [bug]
assignees:
  - Ocelot5836
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the issue
      description: Provide the steps you took to have this issue
      placeholder: |
        1. First do this...
        2. Then this...
        3. Then this happens...
        4. etc.
      render: markdown
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Windows
        - Mac
        - Linux
        - Other
  - type: input
    id: platform_information
    attributes:
      label: Additional Platform Information
      description: Please include additional information about your platform and Java version
      placeholder: ex. Windows 7, Java 11, etc
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste `latest.log` or the relevant crash log here. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: true